### ISSUE TITLE
Core doesn't saves states anymore

### ISSUE THREAD

**Issue by Quickgold74** [libretro/stella2014-libretro#20]
Since 2015-11-26 I can't save anymore RA gave me the message Core does not support saves states.

**Comment by Browner1980** [comment]
This is my first post here and I'm clueless, so I hope I don't get flamed. I just wanted to say that I am experiencing the same issue (on Retropie) - I get the same message in stella re: save states. I only set up Retropie about a month ago so they've never worked for me, but from your post, it seems that save states had worked previously?

**Comment by protoman** [comment]
I also can't save Atari 2600 games states.
Is there any way to update lb-stella to support save-states?
