### ISSUE TITLE
Analog stick support?

### ISSUE THREAD

**Issue by Exalm** [libretro/stella2014-libretro#49]
Since Atari 2600 controller has an analog stick, it would probably make sense to support them.

**Comment by helviojr** [comment]
The CX40 (and CX10) surely is not analog: [Wikipedia - Atari CX40 joystick](https://en.wikipedia.org/wiki/Atari_CX40_joystick). The first analog controller by Atari (with a potenciometer) was for the 5200 in 1982: [Wikipedia - Analog stick](https://en.wikipedia.org/wiki/Analog_stick).

There was the paddle and driving controllers and also a track ball controller launched much later, that are analogs, but no sticks as long as I know/remember.

**Comment by Exalm** [comment]
Right, I was mistaken. :)
