### ISSUE TITLE
Crash on PSVita

### ISSUE THREAD

**Issue by theshinyknight** [libretro/stella2014-libretro#59]
Getting a crash with Stella2014 running on PS vita. Tried with different 2600 roms and neither is able to run; it crash immediately after loading the core

**Comment by Domrael** [comment]
Same problem here, retroarch crashes, only after deleting the Retroarch.cfg file or altering the line:
libretro_path = "app0:/Stella_libretro.self" 
back to:
libretro_path = "app0:/2048_libretro.self"
he starts to work again, since i started to make atari work 4 months ago i never got it

**Comment by aizenar** [comment]
The same happens to me. It seems that the cores of the current stable version (1.9.0) are wrong. It is not a solution, it is just a workaround, but on version 1.8.5, stella and stella 2014 cores are ok, so you can open the 1.8.5 version vpk file with a compressed file manager, grab those core files, and replace them in retroarch core folder. It worked perfectly for me.

**Comment by Domrael** [comment]
I Will try this! Thank you!

**Comment by Domrael** [comment]
Like aizenar Said, anyone trying to run Stella, Just replace the cores for the ones in the 1.8.5, It Will work perfectly!

**Comment by twinaphex** [comment]
We should investigate if this still happens with the latest nightlies.
