### ISSUE TITLE
Feature Request: Paddle joypad sensitivity control.

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/stella2014-libretro#69]
it would be nice to have Paddle joypad sensitivity control so I could play the game astroblast. without it being to fast.

![Capture2-27-2021-8 51 26 AM](https://user-images.githubusercontent.com/21169038/109390764-16c24980-78d9-11eb-8f91-ead86c6d2664.jpg)

**Comment by jdgleaver** [comment]
This should do the trick: https://github.com/libretro/stella2014-libretro/pull/70 :)

**Comment by Cibomatto2002** [comment]
Thank you.
