### ISSUE TITLE
Paddle games do not work.  No support for analog controllers.

### ISSUE THREAD

**Issue by alijani1** [libretro/stella2014-libretro#75]
Standalone Stella (not libretro) works perfectly with paddles as it allows users to map analog gamepad directions to "Paddle 0 Analog", paddle 1 analog, etc, but Stella-libretro does not and it seems libretro forces mapping of analog directional gamepads to just left,right,up,down joystick directions only :(

Please fix Stella-libretro to allow users to map analog controls to Stella analog 0/1/2/3 as its designed to allow.

Its a real shame that we cant play any paddle games and all the systems that use retroarch which uses lr-stella do not support atari paddle games :(

**Comment by alijani1** [comment]
Some additional info.  Basically it looks like only d-pad is mapped to stella joysticks and analog controls on game pads are not mapped at all :(.   all than needs to be done is for the system to map analog controls of retroarch to Paddle 0/1/2/3 analog settings in stella.    Currently games designed for analog controllers (like paddles) are basically unplayable because you have to move left right with d-pad which is really useless.

**Comment by alijani1** [comment]
Hi @jdgleaver , I noticed you added mouse support bach in march, but how is it enabled?  I am not able to get mouse working in stella paddle games.  Any instructions?   

Could you also add support for absolute positioning on analog gamepads please.  currently analog controls  just move left/right/up/down and we really need them to be absolute positioning so we can play paddles style games with precision. currently they are unplayable.

**Comment by jdgleaver** [comment]
> I noticed you added mouse support bach in march, but how is it enabled? I am not able to get mouse working in stella paddle games. Any instructions?

I did not add mouse support - I added support for using the analog stick of a gamepad to control the paddles: https://github.com/libretro/stella2014-libretro/pull/71. This is 'real' analog control, and it works well (for me, at least). There is no special config required - the analog stick 'just works' (although you may wish to adjust the sensitivity via core options). If it is not working for you then either (a) you are running an old build of the core without my commit or (b) you have `Analog to Digital Type` set to `Left Analog` in your input settings (which disables analog input).

If I can find some time, I will look into adding mouse support...

> Could you also add support for absolute positioning on analog gamepads please. currently analog controls just move left/right/up/down and we really need them to be absolute positioning so we can play paddles style games with precision. currently they are unplayable.

The current analog support is relative for a reason. I did try implementing it using absolute positioning, and the result was 100% unusable - it was entirely impossible to control the paddles with any kind of accuracy using a conventional gamepad. Only relative analog positioning works.

If you are referring to absolute positioning for some kind of specialised input hardware that mimics a real paddle, then sorry, but no - I do not own such a device, and I cannot write code that I cannot test...

**Comment by alijani1** [comment]
> If you are referring to absolute positioning for some kind of specialized input hardware that mimics a real paddle, then sorry, but no - I do not own such a device, and I cannot write code that I cannot test...

Hi @jdgleaver. Thank you so much for taking the time to reply.   I disabled analog to digital and made sure I have the correct build and  its working much better but unfortunately the experience is no where close to the standalone Stella, and let my explain.  

BTW, I make and sell USB adapters for retro equipment such as Atari paddles that lets people play these games with original joysticks, driving controllers, and paddles.  I would be happy to send you a FREE unit along with some Atari paddles if you are willing to assist.  See [www.icode.com ](https://www.icode.com/product/9-pin-to-usb-dual-atari-joystick-paddle-and-driving-adapter-by-icode-db9-ports-plus-edition/) for an example adapter I can send you for free.

I made a quick video here that shows the issue more:     [https://youtu.be/H_90k_SJizg](https://youtu.be/H_90k_SJizg)

As you can see in the video, in your implementation as the player say moves say to the right slightly on a paddle device and lets go, on paddles there is no return to center so the object they are controlling on the screen keeps moving to the right.  Absolute positioning for paddles is important for this reason and it makes paddles games very difficult to play with out them and the experience is nothing like the original consoles with relative positioning.  Standalone stella uses absolute positioning so perhaps the reason you had trouble is because you were using a gamepad and not a paddle.

Me and my fans (1000s of people using my devices) would be grateful if you can help us solve this. I get requests daily on why they cant play on retro arch like they do on standalone stella.

You can message with your info and I will ship you a unit.  thank you again in advance, I know its much to ask but people like you make the retro community possible.

**Comment by jdgleaver** [comment]
Ah, okay - I understand the issue here. I guess it would be nice if your paddle hardware emulated mouse input, then adding mouse support would kill two birds with one stone :)

But no matter. Since the paddle is essentially just an analog stick without automatic centring, I don't need any additional hardware for testing. I am busy this week, so cannot give you an ETA yet, but I will put optional absolute positioning on my TODO list.

**Comment by alijani1** [comment]
This issue is now solved with #76 and #78.   Thank you!
