### ISSUE TITLE
Feature request: Make it possible to assign Player 2 controls to Player 1 controller

### ISSUE THREAD

**Issue by ChaosFox1981** [libretro/stella2014-libretro#79]
Right now it is only possible to have the libretro Player 1 control the "left" Atari 2600 joystick/paddle and the libretro Player 2 control the "right" Atari 2600 joystick/paddle. While this seems perfectly logical for a two-player system, the 2600 actually has a boatload of games that used the right joystick port as an extra input method for one-player titles.

For example:
- Spy Hunter needs a joystick plugged into the right port for firing secondary weapons
- Raiders of the Lost Ark uses one for inventory management
- Defender 2 uses it to fire smart bombs
- Solaris uses it to call up the map
- Riddle of the Sphinx needs it for inventory management

Star Raiders also uses the right port for the extra control pad, although as it's a specialised accessory I acknowledge that this may be a bit of a problem.

A workaround for this is to have two controllers connected and to use the second controller accordingly, but unfortunately not everyone has the appropriate hardware, and in my case, the second controller is a crappy €10 thing that keeps getting randomly detected as my Player 1 controller. Another workaround is simply to use standalone Stella for those games (which is what I'm doing), but I need different setups for different games.

Would it be possible to add options to the Player 1 (left) joystick controls that are then passed to the emulator as inputs from the Player 2 (right) joystick port (for example assigned to the right analogue stick on a 360 controller)?

**Comment by hizzlekizzle** [comment]
I think this should be possible now: https://github.com/libretro/RetroArch/pull/12534

**Comment by ChaosFox1981** [comment]
Thank you.

Intriguing news, and interesting timing as this has been on my mind for months but I'd never thought to submit a feature request until now. Good that this is being done at the higher libretro level as I imagine that certain other systems have a similar problem (e.g. C64 games, which chop and change joystick ports from game to game). It looks like they're having a bit of an issue integrating this into Retroarch's config management elegantly but hopefully this will make its way into the next stable release.

I may give the nightly a go.

Closing this for now as I believe the matter is resolved, or at least will be in the near future.
